const MASTER_ITEMS = [
// --- 素材/碎片 (f_001 ~ f_052) ---
{id: "item_ash", name: "灰燼殘渣", img: "f_001.PNG", type: "material", rarity: "T4", price: 10, desc: "合成失敗的產物。"},
{id: "f_wood", name: "粗糙木材", img: "f_002.PNG", type: "fragment", rarity: "T4", price: 100, desc: "森林中常見的木料。"},
{id: "f_iron", name: "鐵礦石", img: "f_003.PNG", type: "fragment", rarity: "T4", price: 150, desc: "含鐵量普通的石頭。"},
{id: "f_water", name: "純淨泉水", img: "f_004.PNG", type: "fragment", rarity: "T4", price: 100, desc: "清澈的飲用水。"},
{id: "f_herb", name: "止血草", img: "f_005.PNG", type: "fragment", rarity: "T4", price: 120, desc: "野外常見的草藥。"},
{id: "f_sand", name: "細沙", img: "f_006.PNG", type: "fragment", rarity: "T4", price: 100, desc: "河邊的普通沙子。"},
{id: "f_feather", name: "飛鳥羽毛", img: "f_007.PNG", type: "fragment", rarity: "T4", price: 120, desc: "普通鳥類的羽毛。"},
{id: "f_slime", name: "黏液球", img: "f_008.PNG", type: "fragment", rarity: "T4", price: 150, desc: "史萊姆留下的痕跡。"},
{id: "f_coal", name: "煤炭塊", img: "f_009.PNG", type: "fragment", rarity: "T4", price: 150, desc: "可燃燒的礦物。"},
{id: "f_glass_s", name: "玻璃碎片", img: "f_010.PNG", type: "fragment", rarity: "T4", price: 120, desc: "破碎的透明材質。"},
{id: "f_copper", name: "銅礦石", img: "f_011.PNG", type: "fragment", rarity: "T4", price: 150, desc: "泛著紅光的礦石。"},
{id: "f_cloth", name: "亞麻布片", img: "f_012.PNG", type: "fragment", rarity: "T4", price: 180, desc: "基礎紡織材料。"},
{id: "f_oil", name: "基礎油脂", img: "f_013.PNG", type: "fragment", rarity: "T4", price: 150, desc: "提煉過的動物油脂。"},
{id: "f_seed", name: "無名種子", img: "f_014.PNG", type: "fragment", rarity: "T4", price: 100, desc: "不知道會長出什麼。"},
{id: "f_bone", name: "野獸碎骨", img: "f_015.PNG", type: "fragment", rarity: "T4", price: 120, desc: "風化後的骨頭。"},
{id: "f_spore", name: "螢光孢子", img: "f_016.PNG", type: "fragment", rarity: "T4", price: 180, desc: "在暗處發出微光。"},
{id: "f_fur", name: "粗硬獸毛", img: "f_017.PNG", type: "fragment", rarity: "T4", price: 150, desc: "保暖效果一般。"},
{id: "f_clay", name: "黏土塊", img: "f_018.PNG", type: "fragment", rarity: "T4", price: 120, desc: "適合塑形的泥土。"},
{id: "f_pebble", name: "光滑鵝卵石", img: "f_019.PNG", type: "fragment", rarity: "T4", price: 100, desc: "經過水流沖刷的石頭。"},
{id: "f_resin", name: "琥珀松脂", img: "f_020.PNG", type: "fragment", rarity: "T4", price: 180, desc: "黏性很強的樹脂。"},
{id: "f_petal", name: "乾枯花瓣", img: "f_021.PNG", type: "fragment", rarity: "T4", price: 100, desc: "失去了原本的鮮豔。"},
{id: "f_silver", name: "銀礦石", img: "f_022.PNG", type: "fragment", rarity: "T3", price: 800, desc: "閃爍銀光的礦石。"},
{id: "f_crystal", name: "魔力水晶碎", img: "f_023.PNG", type: "fragment", rarity: "T3", price: 1000, desc: "蘊含微弱魔力。"},
{id: "f_hardwood", name: "鐵木", img: "f_024.PNG", type: "fragment", rarity: "T3", price: 900, desc: "比鋼鐵還硬的木頭。", recipe: ["p_plank", "p_ingot", "f_oil"]},
{id: "f_silk", name: "幻影絲線", img: "f_025.PNG", type: "fragment", rarity: "T3", price: 1200, desc: "幾乎看不見的細線。", recipe: ["p_rope", "f_spore", "f_slime"]},
{id: "f_ruby_d", name: "紅寶石塵", img: "f_026.PNG", type: "fragment", rarity: "T3", price: 1500, desc: "磨碎的寶石粉末。"},
{id: "f_ice", name: "永凍冰塊", img: "f_027.PNG", type: "fragment", rarity: "T3", price: 1200, desc: "永遠不會融化。", recipe: ["f_water", "p_glass", "f_crystal"]},
{id: "f_obsidian", name: "黑曜石片", img: "f_028.PNG", type: "fragment", rarity: "T3", price: 1100, desc: "鋒利且漆黑。", recipe: ["p_ingot", "f_coal", "f_pebble"]},
{id: "f_gold_d", name: "砂金", img: "f_029.PNG", type: "fragment", rarity: "T3", price: 1500, desc: "河流中篩出的金粒。", recipe: ["f_sand", "p_copper_i", "f_water"]},
{id: "f_scale", name: "亞龍鱗片", img: "f_030.PNG", type: "fragment", rarity: "T3", price: 1300, desc: "來自地底生物的鱗片。"},
{id: "f_leaf", name: "世界樹葉", img: "f_031.PNG", type: "fragment", rarity: "T3", price: 1400, desc: "充滿生命力。", recipe: ["p_fertilizer", "f_wood", "f_seed"]},
{id: "f_element", name: "元素微粒", img: "f_032.PNG", type: "fragment", rarity: "T3", price: 1200, desc: "躁動不安的能量。", recipe: ["f_crystal", "f_spore", "p_lamp"]},
{id: "f_mercury", name: "液態水銀", img: "f_033.PNG", type: "fragment", rarity: "T3", price: 1000, desc: "銀色的液體金屬。", recipe: ["p_ingot", "f_water", "f_coal"]},
{id: "f_leather", name: "硬化皮革", img: "f_034.PNG", type: "fragment", rarity: "T3", price: 900, desc: "經過特殊處理的皮。", recipe: ["f_fur", "f_oil", "p_brush"]},
{id: "f_star", name: "隕星鐵", img: "f_035.PNG", type: "fragment", rarity: "T2", price: 4500, desc: "來自天外的金屬。"},
{id: "f_void", name: "虛空粉末", img: "f_036.PNG", type: "fragment", rarity: "T2", price: 5000, desc: "來自異次元的塵埃。"},
{id: "f_dragon_b", name: "古龍骨", img: "f_037.PNG", type: "fragment", rarity: "T2", price: 4800, desc: "上古巨龍的遺骸。"},
{id: "f_light", name: "聖光碎片", img: "f_038.PNG", type: "fragment", rarity: "T2", price: 4500, desc: "凝固的光芒。"},
{id: "f_dark", name: "暗影精華", img: "f_039.PNG", type: "fragment", rarity: "T2", price: 4500, desc: "濃縮的黑暗。"},
{id: "f_thunder", name: "雷電核心", img: "f_040.PNG", type: "fragment", rarity: "T2", price: 4600, desc: "閃爍著電弧。", recipe: ["f_element", "p_gold_n", "p_lens"]},
{id: "f_spirit", name: "靈魂結晶", img: "f_041.PNG", type: "fragment", rarity: "T2", price: 5000, desc: "純淨的靈魂能量。"},
{id: "f_time", name: "時之沙", img: "f_042.PNG", type: "fragment", rarity: "T2", price: 5000, desc: "流動著時間的沙礫。"},
{id: "f_phoenix", name: "鳳凰羽", img: "f_043.PNG", type: "fragment", rarity: "T2", price: 4800, desc: "永遠燃燒的羽毛。", recipe: ["f_feather", "p_bomb", "p_fuel"]},
{id: "f_titan", name: "泰坦石", img: "f_044.PNG", type: "fragment", rarity: "T2", price: 4600, desc: "極度沉重的石頭。", recipe: ["p_brick", "f_star", "p_gel"]},
{id: "f_divine", name: "秘銀之心", img: "f_045.PNG", type: "fragment", rarity: "T1", price: 0, desc: "金屬彷彿有心跳。", recipe: ["p_sword_h", "f_light", "f_mercury"]},
{id: "f_chaos", name: "混沌之眼", img: "f_046.PNG", type: "fragment", rarity: "T1", price: 0, desc: "注視著深淵。", recipe: ["p_prism", "f_dark", "f_element"]},
{id: "f_eternal", name: "永恆之火", img: "f_047.PNG", type: "fragment", rarity: "T1", price: 0, desc: "永不熄滅的火焰。", recipe: ["p_crown", "p_bomb", "f_star"]},
{id: "f_abyss", name: "深海之淚", img: "f_048.PNG", type: "fragment", rarity: "T1", price: 0, desc: "來自最深海域的悲傷。", recipe: ["p_orb", "f_water", "p_elixir"]},
{id: "f_sky", name: "蒼穹之羽", img: "f_049.PNG", type: "fragment", rarity: "T1", price: 0, desc: "輕如無物。", recipe: ["f_phoenix", "f_silk", "f_element"]},
{id: "f_origin", name: "創世微粒", img: "f_050.PNG", type: "fragment", rarity: "T0", price: 0, desc: "創造世界的基礎粒子。", recipe: ["p_excalibur", "p_sun", "f_void", "f_time"]},
{id: "f_end", name: "終焉之刻", img: "f_051.PNG", type: "fragment", rarity: "T0", price: 0, desc: "象徵萬物終結的符號。", recipe: ["p_gate", "p_trident", "f_dark", "f_chaos"]},

// --- 成品 (p_001 ~ p_047) ---
{id: "p_plank", name: "標準木板", img: "p_001.PNG", type: "product", rarity: "T4", price: 250, desc: "加工後的建材。", recipe: ["f_wood", "f_wood", "f_oil"]},
{id: "p_ingot", name: "鐵錠", img: "p_002.PNG", type: "product", rarity: "T4", price: 350, desc: "鍛造的基礎。", recipe: ["f_iron", "f_iron", "f_coal"]},
{id: "p_water_b", name: "瓶裝泉水", img: "p_003.PNG", type: "product", rarity: "T4", price: 250, desc: "方便攜帶的水源。", recipe: ["f_water", "f_glass_s", "f_glass_s"]},
{id: "p_glass", name: "玻璃板", img: "p_004.PNG", type: "product", rarity: "T4", price: 280, desc: "透明且易碎。", recipe: ["f_sand", "f_sand", "f_coal"]},
{id: "p_arrow", name: "訓練箭矢", img: "p_005.PNG", type: "product", rarity: "T4", price: 300, desc: "練習用的消耗品。", recipe: ["f_wood", "f_feather", "f_slime"]},
{id: "p_gel", name: "凝固膠", img: "p_006.PNG", type: "product", rarity: "T4", price: 350, desc: "用於黏合物品。", recipe: ["f_slime", "f_oil", "f_water"]},
{id: "p_fuel", name: "精煉燃料", img: "p_007.PNG", type: "product", rarity: "T4", price: 350, desc: "燃燒時間更長。", recipe: ["f_coal", "f_oil", "f_wood"]},
{id: "p_copper_i", name: "銅錠", img: "p_008.PNG", type: "product", rarity: "T4", price: 350, desc: "導電性良好的金屬。", recipe: ["f_copper", "f_copper", "f_coal"]},
{id: "p_rope", name: "亞麻繩", img: "p_009.PNG", type: "product", rarity: "T4", price: 400, desc: "結實的繩索。", recipe: ["f_cloth", "f_cloth", "f_oil"]},
{id: "p_torch", name: "手持火把", img: "p_010.PNG", type: "product", rarity: "T4", price: 300, desc: "照亮黑暗。", recipe: ["f_wood", "f_coal", "f_oil"]},
{id: "p_brick", name: "燒製磚塊", img: "p_011.PNG", type: "product", rarity: "T4", price: 280, desc: "堅硬的建築材料。", recipe: ["f_clay", "f_coal", "f_sand"]},
{id: "p_fertilizer", name: "成長肥料", img: "p_012.PNG", type: "product", rarity: "T4", price: 300, desc: "促進植物生長。", recipe: ["f_seed", "f_bone", "f_water"]},
{id: "p_lamp", name: "螢光燈", img: "p_013.PNG", type: "product", rarity: "T4", price: 450, desc: "不用火也能發光。", recipe: ["f_spore", "f_glass_s", "f_oil"]},
{id: "p_brush", name: "毛刷", img: "p_014.PNG", type: "product", rarity: "T4", price: 350, desc: "清潔用的工具。", recipe: ["f_wood", "f_fur", "f_cloth"]},
{id: "p_cup", name: "陶土杯", img: "p_015.PNG", type: "product", rarity: "T4", price: 280, desc: "樸素的容器。", recipe: ["f_clay", "f_clay", "f_water"]},
{id: "p_stone_t", name: "石製工具", img: "p_016.PNG", type: "product", rarity: "T4", price: 250, desc: "原始的加工器具。", recipe: ["f_pebble", "f_wood", "f_rope"]},
{id: "p_amber", name: "人造琥珀", img: "p_017.PNG", type: "product", rarity: "T4", price: 400, desc: "看起來像真的寶石。", recipe: ["f_resin", "f_resin", "f_glass_s"]},
{id: "p_dye", name: "基礎染料", img: "p_018.PNG", type: "product", rarity: "T4", price: 250, desc: "只能染出淡色。", recipe: ["f_petal", "f_water", "f_slime"]},
{id: "p_paper", name: "羊皮紙", img: "p_019.PNG", type: "product", rarity: "T4", price: 400, desc: "紀錄文字的載體。", recipe: ["f_cloth", "f_wood", "f_water"]},
{id: "p_silver_i", name: "純銀錠", img: "p_020.PNG", type: "product", rarity: "T3", price: 2000, desc: "對黑暗生物有效。", recipe: ["f_silver", "f_silver", "p_fuel"]},
{id: "p_lens", name: "水晶透鏡", img: "p_025.PNG", type: "product", rarity: "T3", price: 2500, desc: "可以聚焦魔力。", recipe: ["f_crystal", "p_glass", "p_fuel"]},
{id: "p_wand", name: "學徒法杖", img: "p_026.PNG", type: "product", rarity: "T3", price: 2200, desc: "法師入門裝備。", recipe: ["f_hardwood", "f_crystal", "p_rope"]},
{id: "p_cloth_m", name: "魔法布料", img: "p_027.PNG", type: "product", rarity: "T3", price: 2600, desc: "製作法袍的材料。", recipe: ["f_silk", "f_silk", "p_dye"]},
{id: "p_red_gem", name: "合成紅寶石", img: "p_028.PNG", type: "product", rarity: "T3", price: 3200, desc: "雖然是合成的但很美。", recipe: ["f_ruby_d", "f_ruby_d", "f_ruby_d", "p_gel"]},
{id: "p_frost", name: "冰霜核心", img: "p_029.PNG", type: "product", rarity: "T3", price: 2800, desc: "散發著寒氣。", recipe: ["f_ice", "f_element", "p_glass"]},
{id: "p_dagger", name: "黑曜石匕首", img: "p_030.PNG", type: "product", rarity: "T3", price: 2500, desc: "鋒利無比。", recipe: ["f_obsidian", "f_obsidian", "f_hardwood"]},
{id: "p_gold_n", name: "黃金金塊", img: "p_031.PNG", type: "product", rarity: "T3", price: 3500, desc: "硬通貨。", recipe: ["f_gold_d", "f_gold_d", "f_gold_d", "p_fuel"]},
{id: "p_armor_s", name: "鱗甲片", img: "p_032.PNG", type: "product", rarity: "T3", price: 3000, desc: "堅固的防禦材料。", recipe: ["f_scale", "p_ingot", "p_rope"]},
{id: "p_elixir", name: "生命精華", img: "p_033.PNG", type: "product", rarity: "T3", price: 3200, desc: "濃縮的生命力。", recipe: ["f_leaf", "f_water", "p_water_b"]},
{id: "p_bomb", name: "元素炸彈", img: "p_034.PNG", type: "product", rarity: "T3", price: 2800, desc: "不穩定的爆炸物。", recipe: ["f_element", "f_iron", "p_fuel"]},
{id: "p_mirror", name: "秘銀鏡", img: "p_035.PNG", type: "product", rarity: "T3", price: 2600, desc: "能映照真實。", recipe: ["p_silver_i", "p_lens", "f_mercury"]},
{id: "p_book", name: "附魔書冊", img: "p_036.PNG", type: "product", rarity: "T3", price: 3000, desc: "紀錄魔法的書籍。", recipe: ["p_paper", "f_leather", "p_dye"]},
{id: "p_sword_h", name: "英雄劍胚", img: "p_037.PNG", type: "product", rarity: "T2", price: 12000, desc: "傳說武器的雛形。", recipe: ["f_star", "p_silver_i", "p_fuel", "f_leather"]},
{id: "p_prism", name: "虛空棱鏡", img: "p_038.PNG", type: "product", rarity: "T2", price: 15000, desc: "折射異界之光。", recipe: ["f_void", "p_lens", "p_silver_i"]},
{id: "p_horn", name: "號角", img: "p_039.PNG", type: "product", rarity: "T2", price: 13000, desc: "吹響能震懾野獸。", recipe: ["f_dragon_b", "p_gold_n", "p_amber"]},
{id: "p_cross", name: "聖十字架", img: "p_040.PNG", type: "product", rarity: "T2", price: 11000, desc: "驅散邪惡。", recipe: ["f_light", "p_silver_i", "f_hardwood"]},
{id: "p_cloak", name: "隱形斗篷", img: "p_041.PNG", type: "product", rarity: "T2", price: 14000, desc: "融入陰影之中。", recipe: ["f_dark", "p_cloth_m", "f_silk"]},
{id: "p_hammer", name: "雷神之錘", img: "p_042.PNG", type: "product", rarity: "T2", price: 13500, desc: "蘊含風暴之力。", recipe: ["f_thunder", "f_titan", "f_hardwood", "p_fuel"]},
{id: "p_orb", name: "靈魂寶珠", img: "p_043.PNG", type: "product", rarity: "T2", price: 15000, desc: "儲存靈魂的容器。", recipe: ["f_spirit", "p_glass", "p_gold_n"]},
{id: "p_clock", name: "懷錶", img: "p_044.PNG", type: "product", rarity: "T2", price: 16000, desc: "指針有時會倒轉。", recipe: ["f_time", "p_gold_n", "f_glass_s", "f_mercury"]},
{id: "p_crown", name: "重生冠冕", img: "p_045.PNG", type: "product", rarity: "T2", price: 14500, desc: "象徵不滅的意志。", recipe: ["f_phoenix", "p_gold_n", "p_red_gem"]},
{id: "p_golem", name: "魔像核心", img: "p_046.PNG", type: "product", rarity: "T2", price: 13000, desc: "賦予石頭生命。", recipe: ["f_titan", "f_element", "p_brick"]},
{id: "p_excalibur", name: "王者之劍", img: "p_047.PNG", type: "product", rarity: "T1", price: 0, desc: "統治者的象徵。", recipe: ["f_divine", "p_sword_h", "f_light", "p_gold_n"]},
{id: "p_gate", name: "異界之門", img: "p_048.PNG", type: "product", rarity: "T1", price: 0, desc: "通往未知的微型門戶。", recipe: ["f_chaos", "p_prism", "f_titan", "f_time"]},
{id: "p_sun", name: "太陽圓盤", img: "p_049.PNG", type: "product", rarity: "T1", price: 0, desc: "散發著太陽的高熱。", recipe: ["f_eternal", "p_gold_n", "p_gold_n", "f_light"]},
{id: "p_trident", name: "海皇三叉戟", img: "p_050.PNG", type: "product", rarity: "T1", price: 0, desc: "掌控潮汐之力。", recipe: ["f_abyss", "f_titan", "p_ingot", "f_water"]},
{id: "p_wing", name: "天空之翼", img: "p_051.PNG", type: "product", rarity: "T1", price: 0, desc: "賦予飛行能力。", recipe: ["f_sky", "p_cloth_m", "p_rope"]},
{id: "p_universe", name: "縮微宇宙", img: "p_052.PNG", type: "product", rarity: "T0", price: 0, desc: "掌心裡的星河。", recipe: ["f_origin", "p_prism", "p_orb", "f_element"]},
{id: "p_infinity", name: "無限指環", img: "p_053.PNG", type: "product", rarity: "T0", price: 0, desc: "銜尾蛇造型的戒指。", recipe: ["f_end", "f_time", "p_silver_i", "f_obsidian"]},

// --- 靈獸 (pet_001 ~ pet_020) ---
{id: "pet_wolf", name: "荒原孤狼", img: "pet_001.PNG", type: "pet", rarity: "SP", price: 0, desc: "眼神堅毅的灰狼，旅途的起點。", source: "challenge"},
{id: "pet_bird", name: "青鳥", img: "pet_002.PNG", type: "pet", rarity: "SP", price: 0, desc: "象徵希望的藍色小鳥。", source: "challenge"},
{id: "pet_bear", name: "符文戰熊", img: "pet_003.PNG", type: "pet", rarity: "T3", price: 0, desc: "刻滿符文的巨熊，力大無窮。", recipe: ["p_sword_h", "p_fertilizer", "p_brick"]},
{id: "pet_cat", name: "暗夜獵貓", img: "pet_004.PNG", type: "pet", rarity: "T3", price: 0, desc: "融入黑夜的靈巧貓咪。", recipe: ["p_cloak", "p_gel", "f_fur"]},
{id: "pet_eagle", name: "鋼鐵戰鷹", img: "pet_005.PNG", type: "pet", rarity: "T3", price: 0, desc: "羽毛如鋼鐵般堅硬的老鷹。", recipe: ["p_horn", "p_ingot", "f_feather"]},
{id: "pet_boar", name: "衝鋒野豬", img: "pet_006.PNG", type: "pet", rarity: "T3", price: 0, desc: "橫衝直撞的野獸。", recipe: ["p_brick", "p_fertilizer", "f_bone"]},
{id: "pet_snake", name: "翡翠巨蟒", img: "pet_007.PNG", type: "pet", rarity: "T3", price: 0, desc: "通體碧綠的巨大蟒蛇。", recipe: ["p_crown", "f_herb", "f_scale"]},
{id: "pet_spider", name: "織夢蜘蛛", img: "pet_008.PNG", type: "pet", rarity: "T3", price: 0, desc: "編織夢境的神秘蜘蛛。", recipe: ["f_silk", "p_orb", "p_rope"]},
{id: "pet_fish", name: "深海燈籠魚", img: "pet_009.PNG", type: "pet", rarity: "T3", price: 0, desc: "在深海中引誘獵物。", recipe: ["p_lamp", "f_water", "f_scale"]},
{id: "pet_fox", name: "元素靈狐", img: "pet_010.PNG", type: "pet", rarity: "T3", price: 0, desc: "尾巴燃燒著不同顏色的火焰。", recipe: ["f_element", "f_fur", "p_torch"]},
{id: "pet_lion", name: "皇家獅鷲", img: "pet_011.PNG", type: "pet", rarity: "T2", price: 0, desc: "獅身鷹首的威嚴生物。", recipe: ["p_wing", "p_sword_h", "f_fur", "p_gold_n"]},
{id: "pet_horse", name: "夢魘戰馬", img: "pet_012.PNG", type: "pet", rarity: "T2", price: 0, desc: "腳踏地獄之火的黑馬。", recipe: ["f_dark", "p_clock", "f_bone", "p_fuel"]},
{id: "pet_golem", name: "秘銀魔像", img: "pet_013.PNG", type: "pet", rarity: "T2", price: 0, desc: "全身由秘銀構成的守護者。", recipe: ["p_mirror", "f_titan", "p_ingot"]},
{id: "pet_fairy", name: "森林妖精", img: "pet_014.PNG", type: "pet", rarity: "T2", price: 0, desc: "守護森林的小小精靈。", recipe: ["f_leaf", "f_light", "f_flower"]},
{id: "pet_shark", name: "巨齒狂鯊", img: "pet_015.PNG", type: "pet", rarity: "T2", price: 0, desc: "海洋中的頂級掠食者。", recipe: ["p_trident", "f_scale", "p_ingot"]},
{id: "pet_owl", name: "全知貓頭鷹", img: "pet_016.PNG", type: "pet", rarity: "T2", price: 0, desc: "眼神充滿智慧，通曉古今。", recipe: ["p_book", "p_lens", "f_feather"]},
{id: "pet_dragon", name: "晶紅龍王", img: "pet_017.PNG", type: "pet", rarity: "T1", price: 0, desc: "噴吐烈焰的巨龍之王。", recipe: ["p_sun", "f_dragon_b", "f_eternal", "p_gold_n"]},
{id: "pet_hydra", name: "九頭海蛇", img: "pet_018.PNG", type: "pet", rarity: "T1", price: 0, desc: "擁有強大再生能力的怪獸。", recipe: ["p_trident", "p_orb", "f_abyss", "p_elixir"]},
{id: "pet_phoenix", name: "涅槃鳳凰", img: "pet_019.PNG", type: "pet", rarity: "T1", price: 0, desc: "在灰燼中重生的神鳥。", recipe: ["p_crown", "f_eternal", "f_phoenix", "p_gold_n"]},
{id: "pet_aeon", name: "永恆守護者", img: "pet_020.PNG", type: "pet", rarity: "T0", price: 0, desc: "超越時間與空間的終極存在。", recipe: ["p_universe", "p_infinity", "f_time", "f_light"]}
];
